- hosts: dev
  become: True
  tasks:
  - name: install required system packages
    apt: name={{ item }} state=latest
    loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'gnupg-agent', 'software-properties-common' ]
  
  - name: add apt key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
   
  - name: add docker rep
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu focal stable
      state: present
   
  - name: install docker packages
    apt: name={{ item }} state=latest
    loop: [ 'docker-ce', 'docker-ce-cli', 'containerd.io' ]
      
  - name: install docker py
    pip:
      name: docker-py
      state: absent
      
  - name: del docker
    pip:
      name: docker
      state: absent
      
  - name: install docker py
    pip:
      name: docker
      state: latest
      
  - name: deploy container
    docker_container:
      name: devopsproject
      image: "nebantepermanentnopls/devopsproject:latest"
      state: started
      auto_remove: yes
      published_ports:
        - 80:80
