- hosts: dev
  become: True
  tasks:
  - name: apt update chache
    apt:
      update_cache: yes
      name: docker
      state: latest
      
  - name: deploy container
    docker_container:
      name: simple_index
      image: "nebantepermanentnopls/devopsproject:{{ BUILD_NUMBER }}"
      state: started
      published_ports:
        - 0.0.0.0:80:80
