- hosts: dev
  become: True
  tasks:
#  - name: apt update 
#    apt:
#      update_cache: yes
#      
#  - name: apt upgrade
#    apt:
#      upgrade: full
      
  - name: install pip
    apt:
      name: python3-pip
      state: latest
      
  - name: install docker-py
    pip:
      name: docker-py
      state: latest
      
  - name: install docker
    apt:
      name: docker
      state: latest
      
#  - name: start docker
#    service:
#      name: docker
#      state: started
#      enabled: yes
      
  - name: deploy container
    docker_container:
      name: devopsproject
      image: "nebantepermanentnopls/devopsproject:latest"
      state: started
      auto_remove: yes
      published_ports:
        - 80:80
