- hosts: dev
  become: True
  tasks:
    - name: install pip
    apt:
      update_cache: yes
      
  - name: install pip
    apt:
      upgrade: full
      
  - name: install pip
    apt:
      name: python-pip
      state: latest
      
  - name: install docker-py
    pip:
      name: docker-py
      state: latest
      
  - name: install docker
    apt:
      name: docker
      state: latest
      
  - name: start docker
    service:
      name: docker
      state: started
      enabled: yes
      
  - name: deploy container
    docker_container:
      name: simple_index
      image: "nebantepermanentnopls/devopsproject:{{ BUILD_NUMBER }}"
      state: started
      published_ports:
        - 0.0.0.0:80:80
